hackaton3/urls.py
from django.contrib import admin
from django.urls import path, include

from Email.views import ReviewEmailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('reviews/', ReviewEmailView.as_view(), name="reviews"),
]

users/urls.py
from django.urls import path
from .views import LoginView, SigninView, LogoutView, uploadFileExcel, home_view

app_name = 'users'

urlpatterns = [
    path('', home_view, name='home'),
    path("login/", LoginView.as_view(), name='login'),
    path("signin/", SigninView.as_view(), name='signin'),
    path("logout/", LogoutView.as_view(), name='logout'),
    path("upload/", uploadFileExcel, name='upload'),
]

reservation/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models


# Create your models here.

class Room(models.Model):
    number_room = models.IntegerField()
    state = models.BooleanField(default=False)


class Booking(models.Model):
    date = models.DateField(auto_now=True)
    room = models.ForeignKey(Room, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_booking = models.DateField()
    state = models.BooleanField()

users/models.py
from email.headerregistry import Address
from socket import AF_AX25
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()  # Biography of user

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def create_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def update_profile(sender, instance, **kwargs):
        instance.profile.save()

class UploadFile(models.Model):
    uploadedFile = models.FileField(upload_to='uploads/csv/')
    title=models.CharField(max_length=150)
    date_time_of_upload=models.DateTimeField(auto_now=True)

class Read_excel(models.Model):
    user_id = models.IntegerField()
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.IntegerField()
    address = models.CharField(max_length=100)
    

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django import forms
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):
    pass


class SigninForm(UserCreationForm):
    # username and password are charged for use UserCreationForm
    email = forms.EmailField(label='email')
    first_name = forms.CharField(label='first name')
    last_name = forms.CharField(label='last name')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    

reservation/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from ctypes import addressof
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, RedirectView, FormView, TemplateView, ListView
from .models import Profile, Read_excel
import pandas as pd

import pathlib
from users.forms import LoginForm, SigninForm
from users.models import Profile

from users import models


@login_required(login_url='users:login')
def home_view(request):
    return render(request, 'base.html')


class LoginView(FormView):
    form_class = LoginForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('users:home')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class LogoutView(RedirectView):
    url = reverse_lazy('users:login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, *kwargs)


class SigninView(CreateView):
    form_class = SigninForm
    model = User
    template_name = 'users/signin.html'
    success_url = reverse_lazy('users:login')

def upload_file(request):
    msg = ''
    documents = models.UploadFile.objects.all()
    if request.method == 'POST':
        ext = ['.csv', '.xls', '.xlsx']
        file_title = request.POST["fileTitle"]
        upload_files = request.FILES['uploadedFile']
        # text.csv el csv es el sufijo del archivo
        extension = pathlib.Path(upload_files.name).suffix

        if extension in ext:
            document = models.UploadFile(
                title=file_title,
                uploadedFile=upload_files,
            )

            document.save()
            documents = models.UploadFile.objects.all()  # SELECT * FROM documents
        else:
            document = None
            msg = 'Solo se permiten archivos con extensiones .csv, .xls, .xlsx'
    return render(request, "upload_file.html", context={'files': documents, 'msg': msg})

def uploadFileExcel(request):
    data_excel = None
    msg = ''
    documents = None
    context = None
    if request.method == "POST":
        ext = ['.xls', '.xlsx']
        file_title = request.POST["fileTitle"]
        upload_files = request.FILES['uploadedFile']

        extension = pathlib.Path(upload_files.name).suffix

        if extension in ext:
            document = models.UploadFile(
                title=file_title,
                uploadedFile=upload_files
            )
            document.save()

            data = read_xlsx(document)
            imported_data= pd.DataFrame(data)
            count_data=len(imported_data)  # count rows

            count_userid = imported_data['user_id']  # get dataframe values
            count_userid = count_userid.value_counts()  # get counted values
            count_userid = count_userid.to_frame().to_html


            count_name = imported_data['first_name']  # get dataframe values
            count_name = count_name.value_counts()  # get counted values
            count_name = count_name.to_frame().to_html  # get key list
           
            #  hacer igual que en las lineas 159-161

            count_lastname = imported_data['last_name']  # get dataframe values
            count_lastname = count_lastname.value_counts()
            count_lastname = count_lastname.to_frame().to_html  # get key list
            
            #  hacer igual que en las lineas 159-161

            count_phonenumber = imported_data['phone_number']  # get dataframe values
            count_phonenumber = count_phonenumber.value_counts()
            count_phonenumber = count_phonenumber.to_frame().to_html  # g

            count_address = imported_data['address']  # get dataframe values
            count_address = count_address.value_counts()
            count_address = count_address.to_frame().to_html  # g

            print(count_name)
            context = {'files': data.values.tolist(),
                       'count_data': count_data,
                       'count_userid':count_userid,
                       'count_name': count_name,
                       'count_lastname': count_lastname,
                       'count_phonenumber': count_phonenumber,
                       'count_address': count_address,
                       'msg': msg,
                       }
        else:
            msg = 'Archivo No Valido'
    return render(request, "users/upload_excel.html", context=context)

def read_xlsx(document):
    content = None
    if document:
        content = pd.read_excel(
            document.uploadedFile.path)  # lee el archivo y lo convierte en una lista de diccionarios
        columns = ['user_id', 'first_name', 'last_name', 'phone_number', 'address']
        for data in columns:  # add the column to the object
            if data == "Order Date" or data == "Ship Date":  # reformatea las filas de fecha
                date = pd.to_datetime(content[data]).apply(lambda x: x.date())  # columna reformada
                content[data] = date
        for index, row in content.iterrows():
            Read_excel.objects.create(
                user_id=row['user_id'],
                first_name=row['first_name'],
                last_name=row['last_name'],
                phone_number=row['phone_number'],
                address=row['address'],
                
            ).save()

    return content

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>

<body>
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-black bg-black">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">HOME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="#">Listar Reserva</a>
                <a class="nav-link" >Bienvenid@ {{ user.first_name }}</a>
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>


            </div>
        </div>
    </div>
</nav>
<div class="container py-5">
    {% block content %}
    {% endblock %}
</div>
{% endif %}
</body>
</html>

templates/paginator.html
{% if paginator.num_pages > 1%}
<div class="d-flex justify-content-center">
    <ul class="pagination">
        {% if entity.has_previous %}
            <li class="page-item d-none d-sm-block"><a class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></li>
        {% endif %}
        {% for page in paginator.page_range %}
            {% if forloop.last and page != entity.number and paginator.num_pages > 7 %} 
                {% if entity.next_page_number != paginator.num_pages%}
                <li class="page-item">
                    <a class="page-link" href="?page={{ entity.number | add:1}}#pagtable">...</a>
                </li>
                {% endif %}
            <li class="page-item">
                    <a class="page-link" href="?page={{paginator.num_pages}}#pagtable">{{paginator.num_pages}}</a>
            </li>
            {% endif %}
            {% if page == entity.number and page > 7 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page | add:-1 }}#pagtable">...</a>
            </li>    
            {% endif %}
            {% if page < 7 or page == entity.number %}
            <li class="page-item {% if page == entity.number %}active{% endif %}">
                <a class="page-link" href="?page={{ page }}#pagtable">{{ page }}</a>
            </li>
            {% endif %}
        {% endfor %}
        {% if entity.has_next %}
            <li class="page-item d-none d-sm-block">
                <a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a>
            </li>
        {% endif %}
    </ul>
</div>
<div class="d-flex justify-content-center d-sm-none">            
    {% if entity.has_previous %}
        <span class="page-item"><a  class="page-link" href="?page={{ entity.previous_page_number }}#pagtable">Anterior</a></span>
    {% endif %}
    {% if entity.has_next %}
        <span class="page-item"><a class="page-link" href="?page={{ entity.next_page_number }}#pagtable">Siguiente</a></span>
    {% endif %}
    <br>
    <br>
</div>
{% endif %}

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
{% load crispy_forms_tags  %}
<body>
<div class="container" style="margin-top: 200px">
    <form method="post" action="{% url 'users:login' %}" class="form-control">
        {% csrf_token %}
        <div class="container py-5">
            <h3>Login</h3>
            <div>
                {{ form | crispy }}
            </div>
            <div style="margin-top: 20px">
                <button type="submit" class="btn btn-primary" >Ingresar</button>
                <a href="{% url 'users:signin' %}" class="btn btn-secondary">Register</a>
            </div>
        </div>
    </form>
</div>
</body>
</html>

templates/users/signin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
{% load crispy_forms_tags %}
<body>

<div class="container py-3">
    <h1>Register User</h1>
    <form method="post">
        {% csrf_token %}
        {{ form | crispy }}
        <button class="btn btn-success" type="submit">Save</button>
        <a href="{% url 'users:login' %}" class="btn btn-secondary">Back</a>
    </form>
</div>
</body>
</html>

templates/users/upload_excel.html
{% extends 'base.html' %}

{% block Title %} Upload Files{% endblock %}



{% block content %}
    <div class="d-flex justify-content-center py-4">
        <form method="POST" enctype="multipart/form-data">
            <input type="text" name="fileTitle" placeholder="Enter a title">
            <input type="file" name="uploadedFile">
            {% csrf_token %}
            <input type="submit" value="Upload">
        </form>
    </div>
   
    {% if msg %}
        {{ msg }}
    {% endif %}
    <table class="d-flex justify-content-center">
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>File Path</th>
            <th>Upload Date & Time</th>

        </tr>
        {% for file in files %}
            <tr>
                <td>{{ file.id }}</td>
                <td>{{ file.title }}</td>
                <td>{{ file.uploadedFile.url }}</td>
                <td>{{ file.date_time_of_upload }}</td>
                
            </tr>
        {% endfor %}
    </table>


{% endblock %}